import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { APP_NAME, APP_DESCRIPTION } from "~/lib/constants";
import { getMiniAppEmbedMetadata } from "~/lib/utils";
export const revalidate = 300;

// This is an example of how to generate a dynamically generated share page based on fid:
// Sharing this route e.g. exmaple.com/share/123 will generate a share page for fid 123,
// with the image dynamically generated by the opengraph-image API route.
export async function generateMetadata({
  params,
}: {
  params: Promise<{ fid: string }>;
}): Promise<Metadata> {
  const { fid } = await params;
  // Get base URL - use environment variable or fallback to working domain
  const baseUrl = process.env.NEXT_PUBLIC_URL || 'https://routine-plants-projects-156afffe.vercel.app';
  const imageUrl = `${baseUrl}/api/opengraph-image?fid=${fid}`;

  return {
    title: `${APP_NAME} - Share`,
    openGraph: {
      title: APP_NAME,
      description: APP_DESCRIPTION,
      images: [imageUrl],
    },
    other: {
      // Use fc:miniapp for new Mini Apps (not fc:frame which is legacy)
      "fc:miniapp": JSON.stringify(getMiniAppEmbedMetadata(imageUrl, baseUrl)),
    },
  };
}

export default function SharePage() {
  // redirect to home page
  redirect("/");
}
